version: '3.8'

services:
  db:
    image: postgres:17-alpine 
    restart: always
    environment:
      POSTGRES_DB: quizdb
      POSTGRES_USER: quizuser
      POSTGRES_PASSWORD: quizpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://quizuser:quizpass@db:5432/quizdb
    volumes:
      - ./backend:/app

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: your_email@example.com 
      PGADMIN_DEFAULT_PASSWORD: your_pgadmin_password 
    ports:
      - "8080:80" 
    depends_on:
      - db 
    volumes:
      - pgadmin_data:/var/lib/pgadmin 

volumes:
  pgdata:
  pgadmin_data: 
  
  