"""Change selected_option to Text

Revision ID: 025b9ba32c0f
Revises: 142c1033c7b7
Create Date: 2025-07-24 07:54:11.657259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '025b9ba32c0f'
down_revision = '142c1033c7b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_quiz_answer', schema=None) as batch_op:
        batch_op.alter_column('selected_option',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_quiz_answer', schema=None) as batch_op:
        batch_op.alter_column('selected_option',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1),
               existing_nullable=True)

    # ### end Alembic commands ###

