"""Add quiz history

Revision ID: 142c1033c7b7
Revises: a4ad028e3d29
Create Date: 2025-07-24 07:21:07.552676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '142c1033c7b7'
down_revision = 'a4ad028e3d29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_history')
    # ### end Alembic commands ###

