"""Add level column to Question

Revision ID: 3eb707dd9134
Revises: 025b9ba32c0f
Create Date: 2025-07-29 12:07:33.124336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eb707dd9134'
down_revision = '025b9ba32c0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_quiz', schema=None) as batch_op:
        batch_op.drop_column('level')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))

    # ### end Alembic commands ###

